server.port=8080
spring.application.name=api-gateway

# =========================
# ROUTES
# =========================

# Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=https://quantitymeasurementapp-auth-service-fm3o.onrender.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/users/**,/oauth2/**,/login/**

# QMA Service
spring.cloud.gateway.routes[1].id=qma-service
spring.cloud.gateway.routes[1].uri=https://quantitymeasurementapp-0foy.onrender.com
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/quantities/**

# =========================
# CORS CONFIG
# =========================

spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*

# =========================
# DISABLE EUREKA (IMPORTANT)
# =========================

eureka.client.enabled=false